services:
  t1:
    build: t1
    image: t1
    ports:
      - "8081:8081"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka
  cache-service:
    build: cache-service
    image: cache-service
    ports:
      - "8082:8082"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka
  api-gateway:
    build: api-gateway
    image: gateway
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka
  naming-server:
    build: naming-server
    image: nameserver
    ports:
      - "8761:8761"
    networks:
      - currency-network
networks:
  currency-network:
